name: Updater
run-name: Updating Calendar
on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight

permissions:
  contents: write

jobs:
  Regular-Update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python src/main.py

      - name: Push calendar.ics to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: dist
          build_dir: /
          keep_history: true
          author: BxKangKi <80934730+BxKangKi@users.noreply.github.com>
          commit_message: "docs: update calendar.ics"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
